### ISSUE TITLE
Exception on CTRL+F12

### ISSUE THREAD

**Issue by Stefku** [Stefku/intellij-reference-diagram#6]
```
java.lang.NullPointerException
	at com.intellij.diagram.Utils.getNodeName(Utils.java:182)
	at com.intellij.uml.core.actions.UmlViewStructure.perform(UmlViewStructure.java:46)
	at com.intellij.diagram.DiagramAction.actionPerformed(DiagramAction.java:123)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:586)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:637)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
[  53817]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 14.1.3  Build #IU-141.1010.3 
[  53817]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.7.0_67 
[  53817]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
[  53817]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
[  53817]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 7 
[  53817]  ERROR - llij.ide.plugins.PluginManager - Last Action: UML.ShowStructure 
```

**Comment by Stefku** [comment]
fixed in 1.1.1
