### ISSUE TITLE
Exception  after 'show diagram...'

### ISSUE THREAD

**Issue by pmajkutewicz** [Stefku/intellij-reference-diagram#7]
1. Right click on class method
2. Select show diagram (CTRL+SHIFT+ALT+U)
3. Select "Method reference diagram"
4. Exception is thrown:
```
com.intellij.psi.impl.source.PsiEnumConstantImpl$MyReference cannot be cast to com.intellij.psi.PsiReferenceExpression
java.lang.ClassCastException: com.intellij.psi.impl.source.PsiEnumConstantImpl$MyReference cannot be cast to com.intellij.psi.PsiReferenceExpression
	at ch.docksnet.rgraph.ReferenceDiagramDataModel.wireUpDependencies(ReferenceDiagramDataModel.java:113)
	at ch.docksnet.rgraph.ReferenceDiagramDataModel.prepareReferenceElements(ReferenceDiagramDataModel.java:78)
	at ch.docksnet.rgraph.ReferenceDiagramDataModel.<init>(ReferenceDiagramDataModel.java:54)
	at ch.docksnet.rgraph.ReferenceDiagramProvider.createDataModel(ReferenceDiagramProvider.java:77)
	at ch.docksnet.rgraph.ReferenceDiagramProvider.createDataModel(ReferenceDiagramProvider.java:37)
	at com.intellij.uml.UmlGraphBuilderFactory.create(UmlGraphBuilderFactory.java:26)
	at com.intellij.uml.core.actions.ShowDiagram$1.run(ShowDiagram.java:72)
	at com.intellij.uml.core.actions.ShowDiagramBase$3$1.run(ShowDiagramBase.java:210)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:943)
	at com.intellij.uml.core.actions.ShowDiagramBase$3.run(ShowDiagramBase.java:201)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$14$1.run(ApplicationImpl.java:626)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

Platform info:
```
IntelliJ IDEA (Minerva) IU-143.379.11
Build #IU-143.379, built on October 20, 2015
JRE: 1.8.0_66-b17 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
```

**Comment by Stefku** [comment]
@pmajkutewicz, I think the bug is due to class structure. Is it possible to paste the source code of the class here or send it me via email? If it's non open source, then you could maybe obfuscate the source.
